from src.datachain.query.planner import QueryPlanner

def test_find_join_path_to_common_table_product_customer():
    ...

def test_analyse_context_requires_cte():
    """Check the flag and the measure map"""
    ...

def test_analyse_context_doesnt_require_cte():
    ...

def test_analyse_context_no_measures():
    ...

def test_analyse_context_join_path():
    ...

def test_plan_simple_query_no_cte():
    ...

def test_plan_big_query_no_cte():
    ...

def test_plan_simple_query_cte():
    ...

def test_plan_big_query_cte():
    ...